// Nombres de espalda revisados contra el nombre de origen, equipo y movimiento.
// Las fichas con técnica contradictoria se gestionan por separado.
const reviewed = [
  ["0015", "Asistido parallel agarre cerrado dominada", "Dominadas asistidas con agarre neutro cerrado"],
  ["0017", "Asistido dominada", "Dominadas asistidas en máquina"],
  ["0022", "Pullover a press con barra", "Pullover seguido de press con barra"],
  ["0034", "Declinado flexionado brazo pullover con barra", "Pullover declinado con barra y codos flexionados"],
  ["0037", "Declinado agarre amplio pullover con barra", "Pullover declinado con barra y agarre amplio"],
  ["0064", "Un brazo inclinado remo con barra", "Remo unilateral inclinado con barra"],
  ["0118", "Agarre inverso inclinado remo con barra", "Remo inclinado con barra y agarre supino"],
  ["0150", "Bar lateral jalon con polea", "Jalón al pecho con barra en polea"],
  ["0153", "Cross-sobre lateral jalon con polea", "Jalón cruzado de dorsales en poleas"],
  ["0172", "Inclinado pushdown con polea", "Extensión de tríceps con torso inclinado en polea"],
  ["0159", "Declinado sentado agarre amplio remo con polea", "Remo sentado declinado con agarre amplio en polea"],
  ["0160", "Suelo sentado agarre amplio remo con polea", "Remo sentado en el suelo con agarre amplio en polea"],
  ["0167", "Remo alto (arrodillado) con polea", "Remo alto arrodillado en polea"],
  ["0177", "Lateral jalon (con rope attachment) con polea", "Jalón al pecho con cuerda en polea"],
  ["0180", "Low remo sentado con polea", "Remo bajo sentado en polea"],
  ["0184", "Acostado extensión pullover (con rope attachment) con polea", "Pullover acostado con cuerda en polea"],
  ["0189", "Un brazo inclinado remo con polea", "Remo unilateral inclinado en polea"],
  ["0193", "Un brazo recto espalda remo alto (arrodillado) con polea", "Remo alto unilateral arrodillado en polea"],
  ["0197", "Jalon (pro lat bar) con polea", "Jalón al pecho con barra dorsal en polea"],
  ["0198", "Jalon con polea", "Jalón al pecho en polea"],
  ["0205", "Posterior jalon con polea", "Jalón tras nuca en polea"],
  ["0208", "Agarre inverso recto espalda sentado remo alto con polea", "Remo alto sentado en polea con agarre supino"],
  ["0213", "Sentado remo alto (v-bar) con polea", "Remo alto sentado con barra V en polea"],
  ["0214", "Sentado un brazo alterno remo con polea", "Remo sentado alterno en polea"],
  ["0218", "Sentado agarre amplio remo con polea", "Remo sentado con agarre amplio en polea"],
  ["0234", "De pie remo (v-bar) con polea", "Remo de pie con barra V en polea"],
  ["0236", "De pie giro remo (v-bar) con polea", "Remo de pie con rotación y barra V en polea"],
  ["0237", "Recto brazo jalon (con rope) con polea", "Jalón con brazos rectos y cuerda en polea"],
  ["0238", "Recto brazo jalon con polea", "Jalón con brazos rectos en polea"],
  ["0239", "Recto espalda remo sentado con polea", "Remo sentado con espalda recta en polea"],
  ["0244", "Con giro pull con polea", "Tracción unilateral con rotación en polea"],
  ["0245", "Underhand jalon con polea", "Jalón al pecho con agarre supino en polea"],
  ["0248", "Cambered bar acostado remo", "Remo acostado con barra curva"],
  ["0253", "Chin-ups (narrow parallel agarre)", "Dominadas con agarre neutro cerrado"],
  ["0292", "Un brazo flexionado-sobre remo con mancuernas", "Remo inclinado unilateral con mancuerna"],
  ["0304", "Declinado encogimiento de hombros v. 2 con mancuernas", "Encogimientos con retracción escapular en banco declinado y mancuernas"],
  ["0305", "Declinado encogimiento de hombros con mancuernas", "Encogimientos de hombros en banco declinado con mancuernas"],
  ["0329", "Inclinado encogimiento de hombros con mancuernas", "Encogimientos de hombros en banco inclinado con mancuernas"],
  ["0466", "Gironda sternum chin", "Dominadas al esternón estilo Gironda"],
  ["0498", "Inverted remo con straps", "Remo invertido con correas de suspensión"],
  ["0499", "Inverted remo", "Remo invertido"],
  ["0521", "Alterno renegade remo con kettlebell", "Remo renegado alterno con pesas rusas"],
  ["0522", "Alterno remo con kettlebell", "Remo alterno con pesas rusas"],
  ["0541", "Un brazo remo con kettlebell", "Remo unilateral con pesa rusa"],
  ["0548", "Sumo high pull con kettlebell", "Tirón alto sumo con pesa rusa"],
  ["0558", "Kipping muscle arriba", "Muscle-up con impulso"],
  ["0572", "Máquina de palanca asistido dominada supina", "Dominadas supinas asistidas en máquina"],
  ["0579", "Máquina de palanca frontal jalon", "Jalón frontal en máquina de palanca"],
  ["0580", "Máquina de palanca gripless encogimiento de hombros", "Encogimientos de hombros con agarre neutro en máquina de palanca"],
  ["0581", "Máquina de palanca remo alto", "Remo alto en máquina de palanca"],
  ["0588", "Máquina de palanca narrow agarre remo sentado", "Remo sentado con agarre cerrado en máquina de palanca"],
  ["0604", "Máquina de palanca encogimiento de hombros", "Encogimientos de hombros en máquina de palanca"],
  ["0606", "Máquina de palanca t bar remo", "Remo con barra T en máquina de palanca"],
  ["0627", "Mixed agarre dominada supina", "Dominadas con agarre mixto"],
  ["0631", "Muscle arriba", "Muscle-up en barra"],
  ["0638", "Un brazo dominada supina", "Dominada supina a un brazo"],
  ["0651", "Dominada (neutral agarre)", "Dominadas con agarre neutro"],
  ["0673", "Agarre inverso máquina jalon al pecho", "Jalón al pecho con agarre supino en máquina"],
  ["0674", "Agarre inverso dominada", "Dominadas con agarre supino"],
  ["0680", "Rope climb", "Trepa de cuerda"],
  ["0688", "Scapular dominada", "Dominadas escapulares"],
  ["0690", "Sentado bajar espalda estiramiento", "Estiramiento lumbar sentado"],
  ["0716", "Lateral push cuello estiramiento", "Estiramiento lateral de cuello con ayuda de la mano"],
  ["0746", "Smith espalda encogimiento de hombros", "Encogimientos de hombros con barra detrás en máquina Smith"],
  ["0761", "Smith narrow remo", "Remo con agarre cerrado en máquina Smith"],
  ["0767", "Smith encogimiento de hombros", "Encogimientos de hombros en máquina Smith"],
  ["0794", "De pie lateral estiramiento", "Estiramiento lateral de pie"],
  ["0808", "Suspended remo", "Remo en suspensión"],
  ["0818", "Twin handle parallel agarre jalon al pecho", "Jalón al pecho con doble asa y agarre neutro"],
  ["0970", "Asistido dominada con banda elástica", "Dominadas asistidas con banda elástica"],
  ["0974", "Agarre cerrado jalon con banda elástica", "Jalón con agarre cerrado y banda elástica"],
  ["0983", "Arrodillado un brazo jalon con banda elástica", "Jalón unilateral arrodillado con banda elástica"],
  ["0988", "Un brazo de pie remo bajo con banda elástica", "Remo bajo unilateral de pie con banda elástica"],
  ["0990", "Un brazo con giro remo sentado con banda elástica", "Remo sentado unilateral con rotación y banda elástica"],
  ["1013", "Underhand jalon con banda elástica", "Jalón con agarre supino y banda elástica"],
  ["1313", "Máquina de palanca unilateral remo", "Remo unilateral en máquina de palanca"],
  ["1316", "Flexionado brazo pullover con barra", "Pullover con barra y codos flexionados"],
  ["1317", "Agarre inverso inclinado banco remo con barra", "Remo en banco inclinado con barra y agarre supino"],
  ["1318", "Inclinado banco remo con polea", "Remo en banco inclinado con polea"],
  ["1319", "Palm rotational remo con polea", "Remo con rotación de muñecas en polea"],
  ["1320", "Rope crossover remo sentado con polea", "Remo sentado cruzado con cuerda en polea"],
  ["1321", "Rope elevated remo sentado con polea", "Remo sentado elevado con cuerda en polea"],
  ["1322", "Rope extensión inclinado banco remo con polea", "Remo en banco inclinado con extensión de cuerda en polea"],
  ["1323", "Rope remo sentado con polea", "Remo sentado con cuerda en polea"],
  ["1324", "Upper remo con polea", "Remo alto en polea"],
  ["1325", "Agarre amplio posterior jalon tras nuca con polea", "Jalón tras nuca con agarre amplio en polea"],
  ["1327", "Agarre cerrado dominada supina", "Dominadas supinas con agarre cerrado"],
  ["1328", "Acostado deltoide posterior remo con mancuernas", "Remo acostado para deltoides posteriores con mancuernas"],
  ["1329", "Palm rotational inclinado remo con mancuernas", "Remo inclinado con giro de muñecas y mancuernas"],
  ["1330", "Agarre inverso inclinado banco un brazo remo con mancuernas", "Remo unilateral en banco inclinado con mancuerna y agarre supino"],
  ["1331", "Agarre inverso inclinado banco dos brazo remo con mancuernas", "Remo en banco inclinado con mancuernas y agarre supino"],
  ["1339", "Fitball lat estiramiento", "Estiramiento de dorsales con fitball"],
  ["1341", "Fitball bajar espalda estiramiento (pyramid)", "Estiramiento lumbar sobre fitball"],
  ["1342", "Fitball acostado lateral lat estiramiento", "Estiramiento lateral de dorsales sobre fitball"],
  ["1344", "Ez bar agarre inverso inclinado remo", "Remo inclinado con barra EZ y agarre supino"],
  ["1345", "Dos brazo remo con kettlebell", "Remo con dos pesas rusas"],
  ["1346", "Arrodillado lat estiramiento", "Estiramiento de dorsales arrodillado"],
  ["1347", "Máquina de palanca un brazo lateral amplio jalon", "Jalón unilateral con agarre amplio en máquina de palanca"],
  ["1348", "Máquina de palanca agarre inverso vertical remo", "Remo vertical con agarre supino en máquina de palanca"],
  ["1349", "Máquina de palanca inverso t-bar remo", "Remo con barra T y apoyo de pecho en máquina de palanca"],
  ["1350", "Máquina de palanca remo sentado", "Remo sentado en máquina de palanca"],
  ["1351", "Máquina de palanca t-bar agarre inverso remo", "Remo con barra T y apoyo de pecho en máquina de palanca"],
  ["1353", "Recepción y sobre la cabeza lanzamiento con balon medicinal", "Recepción y lanzamiento por encima de la cabeza con balón medicinal"],
  ["1354", "Sobre la cabeza slam con balon medicinal", "Golpe de balón medicinal contra el suelo desde arriba"],
  ["1355", "Un brazo against wall", "Empuje unilateral isométrico contra pared"],
  ["1356", "Máquina de palanca un brazo lateral remo alto", "Remo alto unilateral en máquina de palanca"],
  ["1358", "Lateral acostado suelo estiramiento", "Estiramiento lateral acostado en el suelo"],
  ["1359", "Smith inclinado remo", "Remo inclinado en máquina Smith"],
  ["1360", "Smith un brazo remo", "Remo unilateral en máquina Smith"],
  ["1361", "Smith agarre inverso inclinado remo", "Remo inclinado con agarre supino en máquina Smith"],
  ["1365", "Upper espalda estiramiento", "Estiramiento de espalda alta"],
  ["1367", "Agarre amplio posterior dominada", "Dominadas tras nuca con agarre amplio"],
  ["1403", "Cuello lateral estiramiento", "Estiramiento lateral de cuello"],
  ["1405", "Espalda pec estiramiento", "Estiramiento de espalda y pecho"],
  ["1429", "Agarre amplio dominada", "Dominadas con agarre amplio"],
  ["1431", "Asistido de pie dominada supina", "Dominadas supinas asistidas de pie"],
  ["1432", "Asistido de pie dominada", "Dominadas asistidas de pie"],
  ["1439", "Máquina de palanca gripless encogimiento de hombros v. 2", "Encogimientos de hombros con respaldo en máquina de palanca"],
  ["1717", "Sentadilla remo (con rope attachment) con polea", "Sentadilla con remo de cuerda en polea"],
  ["1763", "Hombro agarre dominada", "Dominadas con agarre al ancho de hombros"],
  ["1773", "Un brazo toalla remo", "Remo unilateral con toalla"],
  ["2207", "Roller lateral lat estiramiento", "Estiramiento de dorsales con rodillo"],
  ["2285", "Máquina de palanca pullover", "Pullover en máquina de palanca"],
  ["2298", "Inverted remo en banco", "Remo invertido con apoyo en banco"],
  ["2300", "Inverted remo flexionado rodillas", "Remo invertido con rodillas flexionadas"],
  ["2327", "Agarre inverso remo (mujer) con mancuernas", "Remo con mancuernas y agarre supino"],
  ["2330", "Jalon al pecho completo range de motion con polea", "Jalón al pecho con recorrido completo en polea"],
  ["2464", "Thibaudeau kayak remo con polea", "Remo kayak de Thibaudeau en polea"],
  ["2616", "Lateral jalon con v-bar con polea", "Jalón al pecho con barra V en polea"],
  ["2736", "Máquina de palanca agarre inverso lateral jalon", "Jalón al pecho con agarre supino en máquina de palanca"],
  ["2987", "Agarre cerrado dominada supina en fondos estructura con lastre", "Dominadas supinas con agarre cerrado y lastre"],
  ["3010", "Ez bar acostado flexionado brazos pullover", "Pullover acostado con barra EZ y codos flexionados"],
  ["3017", "Remo Pendlay con barra", "Remo Pendlay con barra"],
  ["3116", "Fixed espalda underhand jalon con banda elástica", "Jalón con agarre supino y espalda fija con banda elástica"],
  ["3117", "Fixed espalda agarre cerrado jalon con banda elástica", "Jalón con agarre cerrado y espalda fija con banda elástica"],
  ["3144", "Resistance band sentado recto espalda remo", "Remo sentado con banda elástica y espalda recta"],
  ["3156", "Bodyweight de pie agarre cerrado un brazo remo", "Remo unilateral de pie con agarre cerrado y peso corporal"],
  ["3158", "Bodyweight de pie agarre cerrado remo", "Remo de pie con agarre cerrado y peso corporal"],
  ["3161", "Bodyweight de pie un brazo remo (con toalla)", "Remo unilateral de pie con toalla"],
  ["3162", "Bodyweight de pie un brazo remo", "Remo unilateral de pie con peso corporal"],
  ["3165", "Bodyweight de pie remo (con toalla)", "Remo de pie con toalla"],
  ["3166", "Bodyweight de pie remo", "Remo de pie con peso corporal"],
  ["3167", "Bodyweight squatting remo (con toalla)", "Remo en sentadilla con toalla"],
  ["3168", "Bodyweight squatting remo", "Remo en sentadilla con peso corporal"],
  ["3200", "Máquina de palanca flexionado-sobre remo con v-bar", "Remo inclinado con barra V en máquina de palanca"],
  ["3286", "Muscle arriba con lastre", "Muscle-up con lastre"],
  ["3290", "One hand dominada con lastre", "Dominada a un brazo con lastre"],
  ["3293", "Dominada arquero", "Dominadas arquero"],
  ["3295", "Frontal máquina de palanca reps", "Elevaciones de piernas colgado"],
  ["3297", "Palanca dorsal", "Palanca dorsal"],
  ["3304", "Skin la cat", "Rotación de hombros colgado en barra"],
  ["3312", "Muscle arriba (en bar) con lastre", "Muscle-up en barra con lastre"],
  ["3418", "L-dominada", "Dominadas en L"],
  ["3541", "Inclinado y-elevación con mancuernas", "Elevaciones en Y en banco inclinado con mancuernas"],
  ["3563", "Un brazo jalon con polea", "Jalón unilateral en polea"],
  ["3664", "Lateral plancha con posterior aperturas con mancuernas", "Plancha lateral con apertura posterior y mancuerna"],
  ["3669", "De pie archer", "Movimiento de arquero de pie"],
];

export const BACK_EXERCISE_NAME_CORRECTIONS = Object.freeze(Object.fromEntries(
  reviewed.map(([suffix, from, es]) => [
    `dataset-hasane-${suffix}`,
    { from, es, preserveOld: false },
  ]),
));
