// Nombres de hombros revisados con el nombre inglés, equipo y descripción.
const reviewed = [
  ["0067", "Un brazo arrancada con barra", "Arrancada unilateral con barra"],
  ["0075", "Deltoide posterior elevación con barra", "Elevación para deltoides posteriores con barra"],
  ["0076", "Deltoide posterior remo con barra", "Remo para deltoides posteriores con barra"],
  ["0086", "Sentado tras nuca press militar con barra", "Press militar tras nuca sentado con barra"],
  ["0087", "Sentado bradford rocky press con barra", "Press Bradford sentado con barra"],
  ["0091", "Sentado sobre la cabeza press con barra", "Press de hombros sentado con barra"],
  ["0105", "De pie bradford press con barra", "Press Bradford de pie con barra"],
  ["0107", "De pie elevación frontal sobre la cabeza con barra", "Elevación frontal por encima de la cabeza con barra"],
  ["0123", "Agarre amplio remo al menton con barra", "Remo al mentón con barra y agarre amplio"],
  ["0128", "Battling ropes", "Ondas con cuerdas de batalla"],
  ["0148", "Alterno press de hombros con polea", "Press alterno de hombros en polea"],
  ["0154", "Cross-sobre revers aperturas con polea", "Aperturas inversas cruzadas en polea"],
  ["0162", "Elevación frontal con polea", "Elevación frontal en polea"],
  ["0192", "Un brazo elevación lateral con polea", "Elevación lateral unilateral en polea"],
  ["0202", "Deltoide posterior remo (stirrups) con polea", "Remo para deltoides posteriores con asas en polea"],
  ["0203", "Deltoide posterior remo (con rope) con polea", "Remo para deltoides posteriores con cuerda en polea"],
  ["0215", "Sentado posterior elevación lateral con polea", "Elevación posterior sentado en polea"],
  ["0216", "Sentado hombro rotación interna con polea", "Rotación interna de hombro sentado en polea"],
  ["0225", "De pie cross-sobre high aperturas inversas con polea", "Aperturas inversas cruzadas en polea alta"],
  ["0233", "De pie deltoide posterior remo (con rope) con polea", "Remo de pie para deltoides posteriores con cuerda en polea"],
  ["0235", "De pie hombro rotación externa con polea", "Rotación externa de hombro de pie en polea"],
  ["0240", "Supino aperturas inversas con polea", "Aperturas inversas acostado en polea"],
  ["0286", "Alterno lateral press con mancuernas", "Press lateral alterno con mancuernas"],
  ["0290", "Banco sentado press con mancuernas", "Press de hombros sentado con mancuernas"],
  ["0299", "Cuban press con mancuernas", "Press cubano con mancuernas"],
  ["0311", "Completo can elevación lateral con mancuernas", "Elevación lateral con pulgares arriba y mancuernas"],
  ["0323", "Inclinado un brazo elevación lateral con mancuernas", "Elevación lateral unilateral en banco inclinado con mancuerna"],
  ["0325", "Inclinado elevación con mancuernas", "Press de hombros en banco inclinado con mancuernas"],
  ["0326", "Inclinado posterior elevación lateral con mancuernas", "Elevación posterior en banco inclinado con mancuernas"],
  ["0332", "Iron cross con mancuernas", "Cruz de hierro con mancuernas"],
  ["0335", "Lateral a elevación frontal con mancuernas", "Elevación lateral seguida de frontal con mancuernas"],
  ["0341", "Acostado un brazo deltoid posterior con mancuernas", "Elevación posterior unilateral acostado con mancuerna"],
  ["0345", "Acostado un brazo posterior elevación lateral con mancuernas", "Elevación lateral posterior unilateral acostado con mancuerna"],
  ["0348", "Acostado posterior elevación lateral con mancuernas", "Elevación lateral posterior acostado con mancuernas"],
  ["0355", "Un brazo elevación lateral con mancuernas", "Elevación lateral unilateral con mancuerna"],
  ["0356", "Un brazo elevación lateral con support con mancuernas", "Elevación lateral unilateral con apoyo y mancuerna"],
  ["0359", "Un brazo aperturas inversas (con support) con mancuernas", "Apertura inversa unilateral con apoyo y mancuerna"],
  ["0361", "Un brazo press de hombros con mancuernas", "Press de hombros unilateral con mancuerna"],
  ["0363", "Un brazo remo al menton con mancuernas", "Remo al mentón unilateral con mancuerna"],
  ["0376", "Elevación con mancuernas", "Elevación lateral con mancuernas"],
  ["0377", "Deltoide posterior row_shoulder con mancuernas", "Remo para deltoides posteriores con mancuernas"],
  ["0378", "Posterior aperturas con mancuernas", "Aperturas inversas con mancuernas"],
  ["0379", "Posterior elevación lateral (cabeza apoyada) con mancuernas", "Elevación posterior con cabeza apoyada y mancuernas"],
  ["0380", "Posterior elevación lateral con mancuernas", "Elevación posterior con mancuernas"],
  ["0386", "Rotación aperturas inversas con mancuernas", "Aperturas inversas con rotación y mancuernas"],
  ["0387", "Sentado alterno elevación frontal con mancuernas", "Elevación frontal alterna sentado con mancuernas"],
  ["0388", "Sentado alterno press con mancuernas", "Press de hombros alterno sentado con mancuernas"],
  ["0392", "Sentado elevación frontal con mancuernas", "Elevación frontal sentado con mancuernas"],
  ["0396", "Sentado elevación lateral con mancuernas", "Elevación lateral sentado con mancuernas"],
  ["0404", "Sentado press de hombros (parallel agarre) con mancuernas", "Press de hombros sentado con mancuernas y agarre neutro"],
  ["0405", "Sentado press de hombros con mancuernas", "Press de hombros sentado con mancuernas"],
  ["0408", "Lateral acostado one hand elevación con mancuernas", "Elevación lateral unilateral acostado con mancuerna"],
  ["0414", "De pie alterno sobre la cabeza press con mancuernas", "Press de hombros alterno de pie con mancuernas"],
  ["0415", "De pie alterno elevación con mancuernas", "Elevación alterna de pie con mancuernas"],
  ["0419", "De pie elevación frontal sobre la cabeza con mancuernas", "Elevación frontal por encima de la cabeza con mancuernas"],
  ["0424", "De pie un brazo palm in press con mancuernas", "Press de hombros unilateral de pie con agarre neutro"],
  ["0426", "De pie sobre la cabeza press con mancuernas", "Press de hombros de pie con mancuernas"],
  ["0427", "De pie palms in press con mancuernas", "Press de hombros de pie con mancuernas y agarre neutro"],
  ["0438", "W-press con mancuernas", "Press en W con mancuernas"],
  ["0445", "Ez barbell anti gravity press", "Press de hombros con barra EZ"],
  ["0520", "Alterno press con kettlebell", "Press alterno con pesas rusas"],
  ["0523", "Arnold press con kettlebell", "Press Arnold con pesas rusas"],
  ["0527", "Double jerk con kettlebell", "Jerk con dos pesas rusas"],
  ["0528", "Double push press con kettlebell", "Push press con dos pesas rusas"],
  ["0529", "Double arrancada con kettlebell", "Arrancada con dos pesas rusas"],
  ["0537", "Un brazo cargada y jerk con kettlebell", "Cargada y jerk unilateral con pesa rusa"],
  ["0538", "Un brazo jerk con kettlebell", "Jerk unilateral con pesa rusa"],
  ["0539", "Un brazo press militar a la lateral con kettlebell", "Press militar lateral unilateral con pesa rusa"],
  ["0540", "Un brazo push press con kettlebell", "Push press unilateral con pesa rusa"],
  ["0542", "Un brazo arrancada con kettlebell", "Arrancada unilateral con pesa rusa"],
  ["0546", "Sentado press con kettlebell", "Press de hombros sentado con pesa rusa"],
  ["0547", "Seesaw press con kettlebell", "Press alterno tipo balancín con pesas rusas"],
  ["0550", "Thruster con kettlebell", "Thruster con pesa rusa"],
  ["0552", "Dos brazo cargada con kettlebell", "Cargada con dos pesas rusas"],
  ["0553", "Dos brazo press militar con kettlebell", "Press militar con dos pesas rusas"],
  ["0584", "Máquina de palanca elevación lateral", "Elevación lateral en máquina de palanca"],
  ["0587", "Máquina de palanca press militar", "Press militar en máquina de palanca"],
  ["0590", "Máquina de palanca un brazo press de hombros", "Press de hombros unilateral en máquina de palanca"],
  ["0601", "Máquina de palanca sentado aperturas inversas (parallel agarre)", "Aperturas inversas sentado en máquina con agarre neutro"],
  ["0602", "Máquina de palanca sentado aperturas inversas", "Aperturas inversas sentado en máquina"],
  ["0603", "Máquina de palanca press de hombros", "Press de hombros en máquina de palanca"],
  ["0669", "Posterior deltoid estiramiento", "Estiramiento de deltoides posterior"],
  ["0747", "Smith tras nuca press", "Press tras nuca en máquina Smith"],
  ["0762", "Smith deltoide posterior remo", "Remo para deltoides posteriores en máquina Smith"],
  ["0766", "Smith press de hombros", "Press de hombros en máquina Smith"],
  ["0772", "Smith de pie tras nuca press militar", "Press militar tras nuca de pie en máquina Smith"],
  ["0774", "Smith de pie press militar", "Press militar de pie en máquina Smith"],
  ["0775", "Smith remo al menton", "Remo al mentón en máquina Smith"],
  ["0788", "De pie tras nuca press", "Press tras nuca de pie con barra"],
  ["0844", "Round brazo con lastre", "Círculos de brazos con lastre"],
  ["0863", "Acostado external hombro rotación con mancuernas", "Rotación externa de hombro acostado con mancuerna"],
  ["0864", "Upright hombro rotación externa con mancuernas", "Rotación externa de hombro de pie con mancuernas"],
  ["0869", "Máquina de palanca press de hombros v. 2", "Press de hombros en máquina de palanca con trayectoria inclinada"],
  ["0977", "Frontal elevación lateral con banda elástica", "Elevación lateral frontal con banda elástica"],
  ["1012", "Con giro sobre la cabeza press con banda elástica", "Press de hombros con rotación y banda elástica"],
  ["1017", "Y-elevación con banda elástica", "Elevación en Y con banda elástica"],
  ["1022", "De pie deltoide posterior remo con banda elástica", "Remo de pie para deltoides posteriores con banda elástica"],
  ["1438", "Sentado dos brazo press militar con kettlebell", "Press militar sentado con dos pesas rusas"],
  ["1456", "De pie agarre cerrado press militar con barra", "Press militar de pie con barra y agarre cerrado"],
  ["1457", "De pie amplio press militar con barra", "Press militar de pie con barra y agarre amplio"],
  ["1765", "Remo al menton (espalda pov) con mancuernas", "Remo al mentón con mancuernas"],
  ["2137", "Arnold press con mancuernas", "Press Arnold con mancuernas"],
  ["2143", "De pie around world con mancuernas", "Elevación circular de brazos de pie con mancuernas"],
  ["2271", "Left hook. boxing", "Gancho de izquierda de boxeo"],
  ["2292", "Deltoide posterior elevación con mancuernas", "Elevación para deltoides posteriores con mancuernas"],
  ["2317", "Sentado flexionado brazo elevación lateral con mancuernas", "Elevación lateral sentado con codos flexionados y mancuernas"],
  ["2397", "Scott press con mancuernas", "Press Scott con mancuernas"],
  ["2470", "Acostado en el suelo deltoide posterior elevación con mancuernas", "Elevación para deltoides posteriores acostado en el suelo"],
  ["3237", "Landmine elevación lateral", "Elevación lateral con barra landmine"],
  ["3542", "Inclinado t-elevación con mancuernas", "Elevaciones en T en banco inclinado con mancuernas"],
  ["3546", "Sentado alterno hombro con mancuernas", "Press de hombros tipo balancín sentado con mancuernas"],
  ["3548", "Un brazo sobre la cabeza carry con mancuernas", "Paseo unilateral con mancuerna por encima de la cabeza"],
  ["3641", "Arrodillado paso con swing con lastre", "Balanceo de brazos arrodillado con lastre"],
  ["3697", "Arrodillado deltoide posterior remo (con rope) (hombre) con polea", "Remo arrodillado para deltoides posteriores con cuerda en polea"],
];

export const SHOULDER_EXERCISE_NAME_CORRECTIONS = Object.freeze(Object.fromEntries(
  reviewed.map(([suffix, from, es]) => [`dataset-hasane-${suffix}`, { from, es, preserveOld: false }]),
));
